---
- hosts: all
  become: true

  pre_tasks:
    - name: Config
      include_vars: vars.yml

    - name: apt cache update & Upgrade
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full

  tasks:
    - name: Install packages/prerequisites
      import_tasks: tasks/packages.yml

    - name: Setup Docker.
      import_tasks: tasks/docker.yml

    - name: install portainer
      import_tasks: tasks/portainer.yml
      when: portainer_enable

    - name: install shell in a box
      import_tasks: tasks/shellinabox.yml
      when: shellinabox_enable
    
    - name: install guacamole
      import_tasks: tasks/guacamole.yml
      when: guac_enable

    - name: install homer dashboard
      import_tasks: tasks/homer.yml
      when: homer_enable
